# Generated by Django 4.1.7 on 2023-07-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_postimage_user_usercoverimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postImage',
        ),
    ]
