# Generated by Django 4.1.7 on 2023-07-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_user_userbio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userCoverImage',
            field=models.ImageField(null=True, upload_to='covers_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userProfileImage',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
    ]
