# Generated by Django 4.1.7 on 2023-07-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_user_usercoverimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userCoverImage',
            field=models.ImageField(null=True, upload_to='network/media/covers_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userProfileImage',
            field=models.ImageField(null=True, upload_to='network/media/profile_images/'),
        ),
    ]
