# Generated by Django 4.1.7 on 2023-07-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_user_usercoverimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userBio',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
