# Generated by Django 4.1.7 on 2023-07-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_post_likecount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedPost',
        ),
    ]
