# Generated by Django 4.1.7 on 2023-07-30 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_delete_likedpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post_id', to='network.post')),
                ('userLiked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='happey_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
