# Generated by Django 4.1.7 on 2023-08-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_likedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timePublish',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='likedpost',
            unique_together={('likedPost', 'userLiked')},
        ),
    ]
