# Generated by Django 4.1.7 on 2023-08-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_comment_commenttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postContent',
            field=models.TextField(max_length=10000),
        ),
    ]
