# Generated by Django 4.1.7 on 2023-06-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_watchlist_listing_id_alter_watchlist_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='in_watch',
            field=models.CharField(default=False, max_length=5),
        ),
    ]
