# Generated by Django 4.1.7 on 2023-06-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_bid',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
