# Generated by Django 4.1.7 on 2023-06-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_user_user_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_bid',
        ),
    ]
