# Generated by Django 4.1.7 on 2023-06-06 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='listing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_id_in_category', to='auctions.listing'),
        ),
    ]
